      # используем язык java. Travis CI поддерживает другие языки тоже.
      language: java
      jdk:
        - openjdk11
      os: osx

      # используем режим обычного пользователя для сборки проекта.
      sudo: false

      cache:
        directories:
          - $HOME/.m2

      # после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
      # Здесь используется сторонни сервис https://codecov.io/
      after_success:
        - bash <(curl -s https://codecov.io/bash)

      # Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
      notifications:
        email:
          recipients:
            -swebdesigne@gmail.ru
          on_success: never # default: change
          on_failure: always # default: always
      env:
        global:
          - CODECOV_TOKEN="6a6c7451-04fc-418a-94fc-d4145b0e6163"