language: java

jdk:
  - openjdk15

env:
  global:
    - CODECOV_TOKEN="22384fd3-bfb0-4f76-9789-a804e8d65406"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -rail.swebdesigne@gmail.com
    on_success: never # default: change
    on_failure: always # default: always